In [223]:
from collections import defaultdict, Counter, OrderedDict
import numpy as np
from copy import copy
from itertools import groupby, permutations, product
import json

In [224]:
f = open("inputs/aoc8.txt").read()

In [225]:
def make_data(f):
    data=f.splitlines()
    instructions = data[0]
    nodes = data[2:]
    first_nodes = [node.split(" = ")[0] for node in nodes]
    search_nodes = [node.split(" = ")[1].split(", ") for node in nodes]
    search_nodes = [(node[0].replace("(",""), node[1].replace(")","")) for node in search_nodes]
    return instructions, first_nodes, search_nodes

In [226]:
instructions, first_nodes, search_nodes = make_data(f)

In [227]:
search_nodes[0:5]

[('LRV', 'NBJ'),
 ('PKH', 'PBF'),
 ('PGR', 'CJB'),
 ('XNN', 'GCT'),
 ('QSS', 'PDK')]

In [228]:
instructions

'LRRRLRRLRLLRLRRLRLRLLRRRLRLRRRLRRRLRLRLRRLRLRRRLRRLLRRLLLRRLRRLRRRLRLRRRLRRLRRRLRRRLRRLRLLRRRLRLRRLRLRLRRRLRRLLRRRLLRRLRLRRLRRRLLLRRRLLRLLRRLRRRLRLRLRRLLLRRRLLRRLLLRLRLRRLLRLLRRLLLRRLLRRRLRLRRRLRLLRRRLRRRLRLRLRRRLRLRRRLRRRLRRRLLRLRLRLRRLRLRRRLRLRLLRRLRRLRRLRRRLRRRLRLLRLLLRRLRLRRRR'

# 1

In [229]:
def get_next_node(current_node, instruction):
    index = first_nodes.index(current_node)
    sn = search_nodes[index]
    if instruction=="L":
        next_node = sn[0]
    else:
        next_node = sn[1]
    return next_node      

In [230]:
get_next_node(current_node="AAA", instruction="L")

'SRS'

In [231]:
current_node = "AAA" 
target_node = "ZZZ" 

In [232]:
def get_idx(i):
    l = len(instructions)
    whole_times = i//l
    res = i-whole_times*l
    return res

In [233]:
def test_outcome(current_node, steps):
    for i in np.arange(1,steps+1):    
        instruction = instructions[get_idx(i-1)]
        current_node = get_next_node(current_node,instruction)
    return current_node

In [235]:
test_outcome("MSA", 100000)

'BHF'

# 2

In [236]:
def find_Z(current_node, target_nodes, instruction_index):
    
    counter = 0
    stop=False
    results = []
    all_in_list = False
    limit = 100000
    
    while not stop:
        
        instruction = instructions[instruction_index]
        current_node = get_next_node(current_node, instruction)
        counter = counter+1
        
        # update the instruction index
        instruction_index=instruction_index+1
        if instruction_index==len(instructions):
            instruction_index=0
        
        # determine if to stop
        if set(target_nodes).intersection(set([i[1] for i in results]))==set(target_nodes) or counter>limit:
            stop=True
        else:
            if current_node in target_nodes:
                results.append((current_node,counter))
            
    return results

In [237]:
f = open("inputs/aoc8.txt").read()
instructions, first_nodes, search_nodes = make_data(f)

In [238]:
nodes_A = [n for n in first_nodes if n[2]=="A"]
nodes_Z = [n for n in first_nodes if n[2]=="Z"]
print(nodes_A, nodes_Z)

['MSA', 'AAA', 'PKA', 'NBA', 'RHA', 'CDA'] ['LSZ', 'ZZZ', 'XHZ', 'FHZ', 'RQZ', 'LXZ']


In [239]:
from_a_to_z = list(product(nodes_A, nodes_Z))
from_z_to_z = list(product(nodes_Z, nodes_Z))
combis = from_a_to_z+from_z_to_z

In [242]:
def compute_combis(combis):
    data = defaultdict()

    for combi in combis:
        from_node=combi[0]
        to_node=combi[1]
        print("from: ", from_node, " to:", to_node)
        if not from_node in data:
            data[from_node]=defaultdict()
        if not to_node in data[from_node]:
            data[from_node][to_node] = defaultdict(list)
        
        for idx,instruction in enumerate(instructions[0:1]):            
            instruction = instructions[idx]
            
            count_list = find_Z(from_node, [to_node], idx)
            
            if count_list==[]:
                break
            else:
                data[from_node][to_node][idx]=count_list
                if idx==len(instructions)-1:
                    print(f"Added counts for: {from_node} -> {to_node}")
    
    with open("results.json", "w") as outfile: 
        json.dump(dict(data), outfile)

In [243]:
compute_combis(combis)

from:  MSA  to: LSZ
from:  MSA  to: ZZZ
from:  MSA  to: XHZ
from:  MSA  to: FHZ
from:  MSA  to: RQZ
from:  MSA  to: LXZ
from:  AAA  to: LSZ
from:  AAA  to: ZZZ
from:  AAA  to: XHZ
from:  AAA  to: FHZ
from:  AAA  to: RQZ
from:  AAA  to: LXZ
from:  PKA  to: LSZ
from:  PKA  to: ZZZ
from:  PKA  to: XHZ
from:  PKA  to: FHZ
from:  PKA  to: RQZ
from:  PKA  to: LXZ
from:  NBA  to: LSZ
from:  NBA  to: ZZZ
from:  NBA  to: XHZ
from:  NBA  to: FHZ
from:  NBA  to: RQZ
from:  NBA  to: LXZ
from:  RHA  to: LSZ
from:  RHA  to: ZZZ
from:  RHA  to: XHZ
from:  RHA  to: FHZ
from:  RHA  to: RQZ
from:  RHA  to: LXZ
from:  CDA  to: LSZ
from:  CDA  to: ZZZ
from:  CDA  to: XHZ
from:  CDA  to: FHZ
from:  CDA  to: RQZ
from:  CDA  to: LXZ
from:  LSZ  to: LSZ
from:  LSZ  to: ZZZ
from:  LSZ  to: XHZ
from:  LSZ  to: FHZ
from:  LSZ  to: RQZ
from:  LSZ  to: LXZ
from:  ZZZ  to: LSZ
from:  ZZZ  to: ZZZ
from:  ZZZ  to: XHZ
from:  ZZZ  to: FHZ
from:  ZZZ  to: RQZ
from:  ZZZ  to: LXZ
from:  XHZ  to: LSZ
from:  XHZ  to: ZZZ


In [244]:
with open("results.json", "r") as outfile: 
    data = json.load(outfile)

In [245]:
data

{'MSA': {'LSZ': {},
  'ZZZ': {},
  'XHZ': {'0': [['XHZ', 14893],
    ['XHZ', 29786],
    ['XHZ', 44679],
    ['XHZ', 59572],
    ['XHZ', 74465],
    ['XHZ', 89358]]},
  'FHZ': {},
  'RQZ': {},
  'LXZ': {}},
 'AAA': {'LSZ': {},
  'ZZZ': {'0': [['ZZZ', 20513],
    ['ZZZ', 41026],
    ['ZZZ', 61539],
    ['ZZZ', 82052]]},
  'XHZ': {},
  'FHZ': {},
  'RQZ': {},
  'LXZ': {}},
 'PKA': {'LSZ': {},
  'ZZZ': {},
  'XHZ': {},
  'FHZ': {'0': [['FHZ', 22199],
    ['FHZ', 44398],
    ['FHZ', 66597],
    ['FHZ', 88796]]},
  'RQZ': {},
  'LXZ': {}},
 'NBA': {'LSZ': {'0': [['LSZ', 19951],
    ['LSZ', 39902],
    ['LSZ', 59853],
    ['LSZ', 79804],
    ['LSZ', 99755]]},
  'ZZZ': {},
  'XHZ': {},
  'FHZ': {},
  'RQZ': {},
  'LXZ': {}},
 'RHA': {'LSZ': {},
  'ZZZ': {},
  'XHZ': {},
  'FHZ': {},
  'RQZ': {'0': [['RQZ', 17141],
    ['RQZ', 34282],
    ['RQZ', 51423],
    ['RQZ', 68564],
    ['RQZ', 85705]]},
  'LXZ': {}},
 'CDA': {'LSZ': {},
  'ZZZ': {},
  'XHZ': {},
  'FHZ': {},
  'RQZ': {},
  'LXZ': {'0'

In [46]:
def all_equal(iterable):
    g = groupby(iterable)
    return next(g, True) and not next(g, False)

In [246]:
def get_closest_Z_node(current_index, current_node,data):
    """return the z-node and steps that can be reached with smallest number of steps from current_node,
    given the current_index""" 

    d = data[current_node]
    min_count=10000000000000
    min_current_node = current_node
    
    for target_node in d.keys():
        res=d[target_node][str(current_index)]
        count=res[0]
        node=res[1]
        if count<min_count:
            min_count = count
            min_current_node = node
    return min_count, min_current_node

In [433]:
get_closest_Z_node(14893%len(instructions),"XHZ",data)

(14893, 'XHZ')

In [152]:
def make_distance_path(nodeA, data):
    
    current_node = nodeA
    distance_path = []
    current_index = 0
    i=0
    while i<5:
        count, current_node = get_closest_Z_node(current_index, current_node,data)
        current_index = get_idx(count)
        distance_path.append(count)
        i=i+1
    return distance_path

In [153]:
def iterate(data):
    
    results = []
    s = set()
    for nodeA in nodes_A:
        p = make_distance_path(nodeA,data)
        a = np.array(p).cumsum()
        results.append(a)
    
    return results
    

In [154]:
results =iterate(data)

In [155]:
results

[array([14893, 29786, 44679, 59572, 74465]),
 array([ 20513,  41026,  61539,  82052, 102565]),
 array([ 22199,  44398,  66597,  88796, 110995]),
 array([19951, 39902, 59853, 79804, 99755]),
 array([17141, 34282, 51423, 68564, 85705]),
 array([12083, 24166, 36249, 48332, 60415])]

In [ ]:
a=[0,2,4,6,8]
b

In [115]:
nodes_A

['MSA', 'AAA', 'PKA', 'NBA', 'RHA', 'CDA']

In [131]:
for i,nodeA in enumerate(nodes_A):
    steps = list(results[i])[10]
    print(nodeA, test_outcome(nodes_A[i],steps))

MSA XHZ
AAA ZZZ
PKA FHZ
NBA LSZ
RHA RQZ
CDA LXZ


In [248]:
from math import lcm

In [250]:
lcm(*[14893,20513,22199,19951,17141,12083])

15995167053923